runtime: go115  # or another supported version

instance_class: F2

env_variables:
  KEY: f34a54b3c45ca43c05bb
  PW_SALT_BYTES: 32
  PW_HASH_BYTES: 64

  USER : postgres
  PASSWORD : admin
  CONNECTION_NAME: bep-lingo:europe-west1:lingodb
  DB_NAME: lingo_db

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto



